#!/usr/bin/env bash
set -euo pipefail

OWNER_USER="${POSTGRES_OWNER_USER:-${POSTGRES_USER}}"
OWNER_PASSWORD="${POSTGRES_OWNER_PASSWORD:-${POSTGRES_PASSWORD}}"
MIGRATOR_USER="${POSTGRES_MIGRATION_USER:-pokemon_migrator}"
MIGRATOR_PASSWORD="${POSTGRES_MIGRATION_PASSWORD:-pokemon_migrator_password}"
RUNTIME_USER="${POSTGRES_RUNTIME_USER:-pokemon_runtime}"
RUNTIME_PASSWORD="${POSTGRES_RUNTIME_PASSWORD:-pokemon_runtime_password}"

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${OWNER_USER}') THEN
        EXECUTE format('CREATE ROLE %I NOLOGIN', '${OWNER_USER}');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${MIGRATOR_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${MIGRATOR_USER}', '${MIGRATOR_PASSWORD}');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${RUNTIME_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${RUNTIME_USER}', '${RUNTIME_PASSWORD}');
    END IF;
END
\$\$;

ALTER ROLE ${OWNER_USER} NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
ALTER ROLE ${MIGRATOR_USER} NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
ALTER ROLE ${RUNTIME_USER} NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;

CREATE TABLE IF NOT EXISTS user_feedback (
    feedback_id VARCHAR(64) PRIMARY KEY,
    query_id VARCHAR(128) NOT NULL UNIQUE,
    query TEXT NOT NULL,
    answer TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating IN (-1, 1)),
    comment TEXT,
    model_name VARCHAR(128) NOT NULL,
    latency_seconds DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE user_feedback OWNER TO ${OWNER_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${MIGRATOR_USER};
GRANT USAGE ON SCHEMA public TO ${RUNTIME_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${RUNTIME_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${RUNTIME_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATOR_USER} IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${RUNTIME_USER};
EOSQL
