"""
Core Domain Models for Pokemon TCG RAG.

Defines the stable shared contracts every downstream module codes against:
enums DocumentSource and RuleType, and Pydantic models DocumentMetadata,
Document, Chunk, RetrievedChunk, AnswerResponse, and FeedbackRecord.
"""

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator


class DocumentSource(StrEnum):
    """Source categories for official Pokemon TCG data (9 members)."""

    POKEGYM = "pokegym_rulings"
    RULEBOOK_PDF = "rulebook_pdf"
    TOURNAMENT_HANDBOOK_PDF = "tournament_handbook_pdf"
    ALT_PLAY_HANDBOOK_PDF = "alt_play_handbook_pdf"
    DECK_LIST_GUIDE_PDF = "deck_list_guide_pdf"
    ERRATA_PDF = "errata_pdf"
    BAN_LIST_HTML = "ban_list_html"
    PROMO_LEGALITY_HTML = "promo_legality_html"
    MEGA_RULES_HTML = "mega_rules_html"


class RuleType(StrEnum):
    """Type of ruling or official document content (7 members)."""

    RULING = "ruling"
    GENERAL_RULE = "general_rule"
    TOURNAMENT_RULE = "tournament_rule"
    ERRATA = "errata"
    BAN_STATUS = "ban_status"
    PROMO_STATUS = "promo_status"
    MECHANIC_RULE = "mechanic_rule"


class DocumentMetadata(BaseModel):
    """Metadata schema attached to every indexed document and chunk."""

    model_config = ConfigDict(frozen=True)

    source: DocumentSource
    document_title: str
    page_number: int | None = None
    section_title: str | None = None
    card_name: str | None = None
    rule_type: RuleType = RuleType.GENERAL_RULE
    publication_date: str | None = None
    source_url: str | None = None
    checksum: str | None = None


class Document(BaseModel):
    """Raw extracted document before chunking."""

    doc_id: str
    content: str
    metadata: DocumentMetadata
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @field_validator("content")
    @classmethod
    def content_must_not_be_empty(cls, v: str) -> str:
        """Ensure document content is non-empty."""
        if not v or not v.strip():
            raise ValueError("Document content must not be empty")
        return v


class Chunk(BaseModel):
    """Normalized text chunk ready for embedding and vector database indexing."""

    model_config = ConfigDict(populate_by_name=True)

    chunk_id: str
    doc_id: str = Field(alias="document_id")
    text: str
    token_count: int = 0
    metadata: DocumentMetadata
    embedding: list[float] | None = None

    @field_validator("text")
    @classmethod
    def text_must_not_be_empty(cls, v: str) -> str:
        """Ensure chunk text is non-empty."""
        if not v or not v.strip():
            raise ValueError("Chunk text must not be empty")
        return v

    @property
    def document_id(self) -> str:
        """Backward-compatible alias for the canonical doc_id field."""
        return self.doc_id


class RetrievedChunk(BaseModel):
    """Scored chunk retrieved during search execution."""

    chunk: Chunk
    score: float
    retrieval_method: str  # e.g., 'dense', 'bm25', 'hybrid', 'reranked'


class AnswerResponse(BaseModel):
    """Final answer generated by LLM along with citations and latency metrics."""

    query: str
    rewritten_query: str | None = None
    answer: str
    citations: list[DocumentMetadata]
    retrieved_chunks: list[RetrievedChunk]
    model_name: str
    latency_seconds: float
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def chunks(self) -> list[RetrievedChunk]:
        """Backward-compatible alias for retrieved_chunks."""
        return self.retrieved_chunks


class FeedbackRecord(BaseModel):
    """User feedback entity for RAG monitoring dashboard."""

    feedback_id: str
    query: str
    answer: str
    rating: int = Field(description="1 for thumbs-up, -1 for thumbs-down")
    comment: str | None = None
    model_name: str
    latency_seconds: float
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @field_validator("rating")
    @classmethod
    def rating_must_be_binary(cls, v: int) -> int:
        """Enforce rating ∈ {-1, 1}."""
        if v not in {-1, 1}:
            raise ValueError("rating must be either 1 (positive) or -1 (negative)")
        return v
